name: TSDM 签到任务

on:
  schedule:
    - cron: '0 1 * * *'  # 每天 UTC 1:00 → 北京时间 9:00
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装依赖
        run: pip install httpx beautifulsoup4

      - name: 执行签到脚本
        env:
          COOKIE: ${{ secrets.COOKIE }}
        run: python tsdm_checkin.py
